/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stafaband;

/**
 *
 * @author dimas
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    private static String user;
    public MainView(String username) {
        initComponents();
        user = username;
        txtWelcome.setText("Welcome "+user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit2 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HomeMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CalendarMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TopChartMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TopChartMenu1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TopChartMenu2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NewReleasePanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        TopChartPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        RadioPanel = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(19, 22, 57));
        jPanel1.setPreferredSize(new java.awt.Dimension(256, 768));

        exit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\icMinimize.png")); // NOI18N
        exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        exit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\icExit.png")); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\icFull.png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(145, 147, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(145, 147, 153));
        jLabel3.setText("Browse Music");

        HomeMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeMenu.setOpaque(false);
        HomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(145, 147, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(145, 147, 153));
        jLabel4.setText("Home");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\NAVBAR\\ion_headset.png")); // NOI18N

        javax.swing.GroupLayout HomeMenuLayout = new javax.swing.GroupLayout(HomeMenu);
        HomeMenu.setLayout(HomeMenuLayout);
        HomeMenuLayout.setHorizontalGroup(
            HomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeMenuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeMenuLayout.setVerticalGroup(
            HomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CalendarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalendarMenu.setOpaque(false);
        CalendarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarMenuMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(145, 147, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(145, 147, 153));
        jLabel6.setText("New Release");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\NAVBAR\\feather_calendar.png")); // NOI18N

        javax.swing.GroupLayout CalendarMenuLayout = new javax.swing.GroupLayout(CalendarMenu);
        CalendarMenu.setLayout(CalendarMenuLayout);
        CalendarMenuLayout.setHorizontalGroup(
            CalendarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalendarMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(69, 69, 69))
        );
        CalendarMenuLayout.setVerticalGroup(
            CalendarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TopChartMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TopChartMenu.setOpaque(false);
        TopChartMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopChartMenuMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(145, 147, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(145, 147, 153));
        jLabel8.setText("Top Chart");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\NAVBAR\\bx_bx-line-chart.png")); // NOI18N

        javax.swing.GroupLayout TopChartMenuLayout = new javax.swing.GroupLayout(TopChartMenu);
        TopChartMenu.setLayout(TopChartMenuLayout);
        TopChartMenuLayout.setHorizontalGroup(
            TopChartMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopChartMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(86, 86, 86))
        );
        TopChartMenuLayout.setVerticalGroup(
            TopChartMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TopChartMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TopChartMenu1.setOpaque(false);
        TopChartMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopChartMenu1MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(145, 147, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(145, 147, 153));
        jLabel10.setText("Radio");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\NAVBAR\\mdi_radio-tower.png")); // NOI18N

        javax.swing.GroupLayout TopChartMenu1Layout = new javax.swing.GroupLayout(TopChartMenu1);
        TopChartMenu1.setLayout(TopChartMenu1Layout);
        TopChartMenu1Layout.setHorizontalGroup(
            TopChartMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopChartMenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addGap(86, 86, 86))
        );
        TopChartMenu1Layout.setVerticalGroup(
            TopChartMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TopChartMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TopChartMenu2.setOpaque(false);
        TopChartMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopChartMenu2MouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(145, 147, 153));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(145, 147, 153));
        jLabel12.setText("About");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\NAVBAR\\dashicons_info-outline.png")); // NOI18N

        javax.swing.GroupLayout TopChartMenu2Layout = new javax.swing.GroupLayout(TopChartMenu2);
        TopChartMenu2.setLayout(TopChartMenu2Layout);
        TopChartMenu2Layout.setHorizontalGroup(
            TopChartMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopChartMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addGap(86, 86, 86))
        );
        TopChartMenu2Layout.setVerticalGroup(
            TopChartMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(exit1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exit2)
                        .addGap(8, 8, 8)
                        .addComponent(exit)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(HomeMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CalendarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopChartMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopChartMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopChartMenu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit1)
                    .addComponent(exit2)
                    .addComponent(exit))
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(HomeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CalendarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(TopChartMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(TopChartMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(TopChartMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(9, 12, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(1110, 94));

        txtWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcome.setText("Welcome,  Dimas.");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\INPUT\\logout.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(txtWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtWelcome))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(5, 7, 28));
        MainPanel.setPreferredSize(new java.awt.Dimension(1110, 674));
        MainPanel.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(5, 7, 28));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\TITLE\\ion_headset (1).png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Home");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\big.png")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-2.png")); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-1.png")); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-3.png")); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-4.png")); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15))
                    .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(HomePanelLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel17)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(42, 42, 42)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        MainPanel.add(HomePanel, "card2");

        NewReleasePanel.setBackground(new java.awt.Color(5, 7, 28));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\TITLE\\feather_calendar (1).png")); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("New Release");

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-5.png")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-6.png")); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-7.png")); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-8.png")); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-1.png")); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-2.png")); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-3.png")); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-4.png")); // NOI18N

        javax.swing.GroupLayout NewReleasePanelLayout = new javax.swing.GroupLayout(NewReleasePanel);
        NewReleasePanel.setLayout(NewReleasePanelLayout);
        NewReleasePanelLayout.setHorizontalGroup(
            NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewReleasePanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewReleasePanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel29)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel30)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel31))
                    .addGroup(NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NewReleasePanelLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewReleasePanelLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel25)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel26)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel27))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        NewReleasePanelLayout.setVerticalGroup(
            NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewReleasePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(40, 40, 40)
                .addGroup(NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(40, 40, 40)
                .addGroup(NewReleasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        MainPanel.add(NewReleasePanel, "card3");

        TopChartPanel.setBackground(new java.awt.Color(5, 7, 28));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\TITLE\\bx_bx-line-chart (1).png")); // NOI18N

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Top Chart");

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-1.png")); // NOI18N

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-2.png")); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-3.png")); // NOI18N

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-4.png")); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-8.png")); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-7.png")); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-6.png")); // NOI18N

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-5.png")); // NOI18N

        javax.swing.GroupLayout TopChartPanelLayout = new javax.swing.GroupLayout(TopChartPanel);
        TopChartPanel.setLayout(TopChartPanelLayout);
        TopChartPanelLayout.setHorizontalGroup(
            TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopChartPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TopChartPanelLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel34)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel35)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel36))
                    .addGroup(TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopChartPanelLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel32))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopChartPanelLayout.createSequentialGroup()
                            .addComponent(jLabel40)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel39)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel38)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel37))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        TopChartPanelLayout.setVerticalGroup(
            TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopChartPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel23))
                .addGap(40, 40, 40)
                .addGroup(TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(40, 40, 40)
                .addGroup(TopChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        MainPanel.add(TopChartPanel, "card4");

        RadioPanel.setBackground(new java.awt.Color(5, 7, 28));

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\TITLE\\mdi_radio-tower (1).png")); // NOI18N

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Radio");

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-1.png")); // NOI18N

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-2.png")); // NOI18N

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-3.png")); // NOI18N

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-4.png")); // NOI18N

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-8.png")); // NOI18N

        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-7.png")); // NOI18N

        jLabel49.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-6.png")); // NOI18N

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\dimas\\Downloads\\Assets\\small-5.png")); // NOI18N

        javax.swing.GroupLayout RadioPanelLayout = new javax.swing.GroupLayout(RadioPanel);
        RadioPanel.setLayout(RadioPanelLayout);
        RadioPanelLayout.setHorizontalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RadioPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RadioPanelLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel44)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel45)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel46))
                    .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RadioPanelLayout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadioPanelLayout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel49)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel48)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel47))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        RadioPanelLayout.setVerticalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RadioPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41))
                .addGap(40, 40, 40)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(40, 40, 40)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50)
                    .addComponent(jLabel48)
                    .addComponent(jLabel47))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        MainPanel.add(RadioPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exit2MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LoginView login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void HomeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(HomePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_HomeMenuMouseClicked

    private void CalendarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarMenuMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(NewReleasePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_CalendarMenuMouseClicked

    private void TopChartMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopChartMenuMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(TopChartPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_TopChartMenuMouseClicked

    private void TopChartMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopChartMenu1MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(RadioPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_TopChartMenu1MouseClicked

    private void TopChartMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopChartMenu2MouseClicked
        // TODO add your handling code here:
        AboutView about = new AboutView();
        about.setVisible(true);
    }//GEN-LAST:event_TopChartMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalendarMenu;
    private javax.swing.JPanel HomeMenu;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NewReleasePanel;
    private javax.swing.JPanel RadioPanel;
    private javax.swing.JPanel TopChartMenu;
    private javax.swing.JPanel TopChartMenu1;
    private javax.swing.JPanel TopChartMenu2;
    private javax.swing.JPanel TopChartPanel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
